Projeto_Pet/TCC/Controllers/AreaFuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TCC.Dados;
using TCC.Models;

namespace TCC.Controllers
{
    public class AreaFuncionarioController : Controller
    {
        acFuncionario acF = new acFuncionario();

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(ModelFuncionario cm)
        {
            acF.TestarUsuario(cm); // Verificar se usu e senha estão corretos

            if (cm.login != null && cm.senha != null)
            {

                FormsAuthentication.SetAuthCookie(cm.login, false);
                
                Session["usu"] = cm.nivel_func;
                Session["usuName"] = cm.nm_func;
                Session["usuImg"] = cm.image_func;


                if (cm.nivel_func == "admin")
                {
                    Session["admin"] = cm.nivel_func;
                }
                else
                {
                    Session["comum"] = cm.nivel_func;
                }


                return RedirectToAction("Index", "Funcionario");
            }
            else
            {
                ViewBag.msgLogar = "Login Incorreto. Verifique o login e a senha";
                return View();
            }
        }

        public ActionResult Logout()
        {
            Session["usu"] = null;
            Session["usuName"] = null;
            Session["usuImg"] = null;
            return RedirectToAction("Index", "Home");

        }

        public ActionResult About()
        {
            ViewBag.usuName = Session["usuName"];
            ViewBag.usuImg = Session["usuImg"];
            if (Session["usu"] == null)

            {
                return RedirectToAction("SemAcesso", "Cliente");
            }
            else
            {
                ViewBag.Message = "Your application description page.";
                ViewBag.usuarioLogado = Session["usu"];
                return View();
            }
        }

        public ActionResult Contact()
        {
            ViewBag.usuName = Session["usuName"];
            ViewBag.usuImg = Session["usuImg"];
            if (Session["usu"] == null)

            {
                return RedirectToAction("SemAcesso", "Cliente");
            }
            else
            {
                if (Session["comum"] == null)
                {
                    ViewBag.Message = "Your contact page.";

                    return View();
                }
                else
                {
                    return RedirectToAction("SemAcesso", "Cliente");
                }
            }
        }

        public ActionResult SemAcesso()
        {
            return View();
        }

    }
}

Projeto_Pet/TCC/Views/AreaFuncionario/Index.cshtml
@model TCC.Models.ModelFuncionario
@{
    ViewBag.Title = "Index";
}
@{
    Layout = null;
}
@ViewBag.confCadastro
@ViewBag.msgLogar

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Styles/loginCliente.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;500;600;700&display=swap" rel="stylesheet">
    <title>Entrar na conta - AnimalCity</title>

    <style>
        .link-func {
            position: absolute;
            top: 2rem;
            right: 2rem;
        }

            .link-func a {
                color: #960036;
            }
    </style>
</head>

<body>
    <main>
        <div class="center">
            <h1>Login</h1>
            @using (Html.BeginForm("Index", "AreaFuncionario", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="txt_field">
                    @Html.EditorFor(model => model.login, new { htmlAttributes = new { @class = "input", @required = true, @placeholder = " " } })
                    <span></span>
                    <label>Email</label>
                </div>
                <div class="txt_field">
                    @Html.EditorFor(model => model.senha, new { htmlAttributes = new { @class = "input", @required = true, @placeholder = " ", @type = "password" } })
                    <span></span>
                    <label>Senha</label>
                </div>
                <input type="submit" value="Entrar">
                <strong>
                    @ViewBag.msg
                </strong>

            }
        </div>
    </main>
</body>
</html>