Projeto_Pet/TCC/Controllers/CompraController.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TCC.Dados;
using TCC.Models;


namespace TCC.Controllers
{
    public class CompraController : Controller
    {
        AcoesProduto acProd = new AcoesProduto();
        acCarrinho acCar = new acCarrinho();
        AcoesCompra acComp = new AcoesCompra();
        
     
        

        public ActionResult Index()
        {
            return View();
        }

        public static string codigo;
        public static double Qt;

        public void carregaPag()
        {
            List<SelectListItem> pagamento = new List<SelectListItem>();

            using (MySqlConnection con = new MySqlConnection("Server=localhost;DataBase=bd_eAnimalcity;User=root;pwd=S!A@i3r4"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("select * from tbl_pagamento", con);
                MySqlDataReader rdr = cmd.ExecuteReader();

                while (rdr.Read())
                {
                    pagamento.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });
                }
                con.Close();

            }
            ViewBag.pagamento = new SelectList(pagamento, "Value", "Text");
        }


        public ActionResult AdicionarCarrinho(int id, double pre)
        {
            if (Session["logged"] == null)
            {
                return RedirectToAction("LoginCliente", "Cliente");

            }
            ViewBag.usuName = Session["usuName"];
            ViewBag.usuImage = Session["usuImg"];

            ModelCompra carrinho = Session["Carrinho"] != null ? (ModelCompra)Session["Carrinho"] : new ModelCompra();
            var produto = acProd.GetConsProd(id);
            codigo = id.ToString();

            ModelProduto prod = new ModelProduto();


            if (produto != null)
            {
                var itemPedido = new ModelCarrinho();
                itemPedido.ItemPedidoID = Guid.NewGuid();
                itemPedido.cd_produto = id.ToString();
                itemPedido.nm_produto = produto[0].nm_produto;
                itemPedido.qt_venda = 1;
                itemPedido.vl_unitario = pre;

                List<ModelCarrinho> x = carrinho.ItensPedido.FindAll(l => l.nm_produto == itemPedido.nm_produto);

                if (x.Count != 0)
                {
                    carrinho.ItensPedido.FirstOrDefault(p => p.nm_produto == produto[0].nm_produto).qt_venda += 1;
                    itemPedido.vl_parcial = itemPedido.qt_venda * itemPedido.vl_unitario;
                    carrinho.vlTotal += itemPedido.vl_parcial;
                    carrinho.ItensPedido.FirstOrDefault(p => p.nm_produto == produto[0].nm_produto).vl_parcial = carrinho.ItensPedido.FirstOrDefault(p => p.nm_produto == produto[0].nm_produto).qt_venda * itemPedido.vl_unitario;
                }

                else
                {
                    itemPedido.vl_parcial = itemPedido.qt_venda * itemPedido.vl_unitario;
                    carrinho.vlTotal += itemPedido.vl_parcial;
                    carrinho.ItensPedido.Add(itemPedido);
                }

                /*carrinho.ValorTotal = carrinho.ItensPedido.Select(i => i.Produto).Sum(d => d.Valor);*/

                Session["Carrinho"] = carrinho;
            }

            return RedirectToAction("Carrinho");
        }
        public ActionResult RetirarCarrinho(int id, double pre)
        {
            ModelCompra carrinho = Session["Carrinho"] != null ? (ModelCompra)Session["Carrinho"] : new ModelCompra();
            var produto = acProd.GetConsProd(id);
            codigo = id.ToString();

            ModelProduto prod = new ModelProduto();

            if (produto != null)
            {
                var itemPedido = new ModelCarrinho();
                itemPedido.ItemPedidoID = Guid.NewGuid();
                itemPedido.cd_produto = id.ToString();
                itemPedido.nm_produto = produto[0].nm_produto;
                itemPedido.qt_venda = 1;
                itemPedido.vl_unitario = pre;

                List<ModelCarrinho> x = carrinho.ItensPedido.FindAll(l => l.nm_produto == itemPedido.nm_produto);

                if (x.Count != 0)
                {
                    if (carrinho.ItensPedido.FirstOrDefault(p => p.nm_produto == produto[0].nm_produto).qt_venda > 1)
                    {
                        carrinho.ItensPedido.FirstOrDefault(p => p.nm_produto == produto[0].nm_produto).qt_venda -= 1;
                        itemPedido.vl_parcial = itemPedido.qt_venda * itemPedido.vl_unitario;
                        carrinho.vlTotal -= itemPedido.vl_parcial;
                        carrinho.ItensPedido.FirstOrDefault(p => p.nm_produto == produto[0].nm_produto).vl_parcial = carrinho.ItensPedido.FirstOrDefault(p => p.nm_produto == produto[0].nm_produto).qt_venda * itemPedido.vl_unitario;
                    }
                }
                else
                {
                    itemPedido.vl_parcial = itemPedido.qt_venda * itemPedido.vl_unitario;
                    carrinho.vlTotal += itemPedido.vl_parcial;
                    carrinho.ItensPedido.Add(itemPedido);
                }

                /*carrinho.ValorTotal = carrinho.ItensPedido.Select(i => i.Produto).Sum(d => d.Valor);*/

                Session["Carrinho"] = carrinho;
            }


            return RedirectToAction("Carrinho");
        }

        public ActionResult Carrinho(ModelCompra x)
        {
            ViewBag.usuName = Session["usuName"];
            ViewBag.usuImage = Session["usuImg"];
            ModelCompra carrinho = Session["Carrinho"] != null ? (ModelCompra)Session["Carrinho"] : new ModelCompra();
            carregaPag();
            x.cdPagamento = Request["pagamento"];
            x.vlTotal = carrinho.vlTotal;
            return View(carrinho);
        }

        public ActionResult ExcluirItem(Guid id)
        {
            var carrinho = Session["Carrinho"] != null ? (ModelCompra)Session["Carrinho"] : new ModelCompra();
            var itemExclusao = carrinho.ItensPedido.FirstOrDefault(i => i.ItemPedidoID == id);

            carrinho.vlTotal = itemExclusao.vl_parcial;

            carrinho.ItensPedido.Remove(itemExclusao);

            Session["Carrinho"] = carrinho;
            return RedirectToAction("Carrinho");
        }

        public ActionResult SalvarCarrinho(ModelCompra x)
        {
            carregaPag();
            if (Session["logged"] == null)
            {
                return RedirectToAction("LoginCliente", "Cliente");

            }
            else
            {
                ViewBag.usuName = Session["usuName"];
                ViewBag.usuImage = Session["usuImg"];
                var carrinho = Session["Carrinho"] != null ? (ModelCompra)Session["Carrinho"] : new ModelCompra();

                ModelCompra md = new ModelCompra();
                ModelCarrinho mdV = new ModelCarrinho();

                md.dtCompra = DateTime.Now.ToLocalTime().ToString("dd/MM/yyyy");
                md.cdClienteCompra = Session["codCliente"].ToString();
                md.vlTotal = carrinho.vlTotal;
                md.cdPagamento = Request["pagamento"];
                acComp.inserirCompra(md);


                acComp.buscaIdCompra(x);
              

                for (int i = 0; i < carrinho.ItensPedido.Count; i++)
                { 
                    mdV.cd_compra = x.cdCompra;
                    mdV.cd_pagamento = Request["pagamento"];
                    mdV.cd_produto = carrinho.ItensPedido[i].cd_produto;
                    mdV.qt_venda = carrinho.ItensPedido[i].qt_venda;
                    mdV.vl_parcial = carrinho.ItensPedido[i].vl_parcial;
                    mdV.vl_total = md.vlTotal;
                    mdV.dt_compra = md.dtCompra;
                    acCar.inserirCarrinho(mdV);
                }

                carrinho.ItensPedido.Clear();
                return RedirectToAction("confVenda");
            }
        }

        public ActionResult confVenda()
        {
            return View();
        }



    }
}

Projeto_Pet/TCC/Controllers/LojaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TCC.Models;
using TCC.Dados;
using System.IO;
using System.Web.Security;
using System.Text.RegularExpressions;
using MySql.Data.MySqlClient;


namespace TCC.Controllers
{
    public class LojaController : Controller
    {

        AcoesProduto acProd = new AcoesProduto();
        AcoesLoginCliente acCliente = new AcoesLoginCliente();

        public void selecionaCliente(ModelCliente cm)
        {
            cm.cdCliente = Session["codCliente"].ToString();
            acCliente.ObterInformacoesCliente(cm);
            ViewBag.nome = cm.nmCliente;
            ViewBag.email = cm.emailCliente;
            ViewBag.senha = cm.senha;
            ViewBag.img = cm.imageCliente;
            ViewBag.cpf = cm.cpf_cliente;

            ViewBag.tel = cm.noTelefone;

            ViewBag.cep = cm.noCep;
            ViewBag.nmLog = cm.nmlogradouro;
            ViewBag.noLog = cm.noLogradouro;

            ViewBag.bairro = cm.nmBairro;
            ViewBag.comp = cm.dsComplemento;
        }

        public void carregaCategoria()
        {
            List<SelectListItem> categoria = new List<SelectListItem>();

            using (MySqlConnection con = new MySqlConnection("Server=localhost; DataBase=bd_eAnimalcity; User=root; pwd=S!A@i3r4"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("select * from tbl_categoria", con);
                MySqlDataReader rdr = cmd.ExecuteReader();

                while (rdr.Read())
                {
                    categoria.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });
                }
                con.Close();

            }

            ViewBag.categoria = new SelectList(categoria, "Value", "Text");
        }

        public ActionResult Index(ModelProduto cmP, ModelCliente cm)
        {
            if (Session["logged"] == null)
            {
                carregaCategoria();
                return View(acProd.GetProduto(cmP));
            }
            else
            {
                carregaCategoria();
                ViewBag.usuName = Session["usuName"];
                ViewBag.usuImage = Session["usuImg"];
                carregaCategoria();
                return View(acProd.GetProduto(cmP));

            }
        }

        [HttpPost]
        public ActionResult Index(ModelProduto cmP, ModelCliente cm, string id)
        {
            if (Session["logged"] == null)
            {
                carregaCategoria();

                if(Request["categoria"] == "")
                {
                    return View(acProd.GetProduto(cmP));
                }

                cmP.cd_categoria = Request["categoria"];
                return View(acProd.GetProdutoPorCategoria(cmP));
            }
            else
            {
                carregaCategoria();
                ViewBag.usuName = Session["usuName"];
                ViewBag.usuImage = Session["usuImg"];
                carregaCategoria();
                if (Request["categoria"] == "")
                {
                    return View(acProd.GetProduto(cmP));
                }
                cmP.cd_categoria = Request["categoria"];
                return View(acProd.GetProdutoPorCategoria(cmP));

            }
        }

        [HttpPost]
        public ActionResult BuscaProduto(ModelProduto cm, FormCollection frm)
        {
            if (Session["logged"] == null)
            {
                carregaCategoria();

                cm.nm_produto = frm["textBusca"];
                return View(acProd.GetProdutoPorBusca(cm));
            }
            else
            {
                carregaCategoria();
                ViewBag.usuName = Session["usuName"];
                ViewBag.usuImage = Session["usuImg"];
                carregaCategoria();
                cm.nm_produto = frm["textBusca"];
                return View(acProd.GetProdutoPorBusca(cm));

            }
        }


        public ActionResult ProductDetails(ModelProduto cm, string id)
        {
            if (Session["logged"] == null)
            {
                cm.cd_produto = id;
                acProd.ShowProductDetails(cm);
                ViewBag.nmProd = cm.nm_produto;
                ViewBag.imageProd = cm.image_produto;
                ViewBag.marcaProd = cm.marca_produto;
                ViewBag.dsProd = cm.ds_prod;
                ViewBag.precoProd = cm.vl_produto;
                return View();
            }
            else
            {
                cm.cd_produto = id;
                acProd.ShowProductDetails(cm);
                ViewBag.nmProd = cm.nm_produto;
                ViewBag.imageProd = cm.image_produto;
                ViewBag.marcaProd = cm.marca_produto;
                ViewBag.dsProd = cm.ds_prod;
                ViewBag.precoProd = cm.vl_produto;
                ViewBag.usuName = Session["usuName"];
                ViewBag.usuImage = Session["usuImg"];
                return View();

            }
        }


    }
}

Projeto_Pet/TCC/Views/Compra/AdicionarCarrinho.cshtml
@{
    ViewBag.Title = "AdicionarCarrinho";
}

<h2>AdicionarCarrinho</h2>

Projeto_Pet/TCC/Views/Compra/Carrinho.cshtml
@model TCC.Models.ModelCompra
@{
    ViewBag.Title = "Carrinho";
}


<style>
    .container-my{
        padding: 6rem 2rem;
        min-height: 100vh;
    }

    .table-my {
        width: 100%;
        margin: 0 auto !important;

    }

    .items-text{
        width: 100% !important;
        display: flex;
        background: #f1f1f1;
        padding: 20px !important;
        text-align: left !important;
    }

    .items-text td{
        width: 250px !important;
    }

    .cab-my {
        background: #474747;
        color: #fff;
    }

    .remover a {
        background: red;
        color: #fff;
        width: 100px;
        border-radius: .25rem;
        padding: 10px;
    }

    .pagamento select {
        margin-top: 1rem !important;
        padding: 10px;
        border: 2px solid #c4c4c4;
        border-radius: .25rem;
        margin-bottom: 1rem !important;
    }

    hr {
        height: 2px;
        width: 100%;
        background: #C4C4C4;
        margin-top: 2rem !important;
        margin-bottom: 2rem !important;
    }

    .links-items{
        display: flex;
        flex-direction:column;
    }

    .first-ch a {
        display: block;
        padding: 10px !important;
        width: 305px;
        text-align: center;
        color: #272727;
        border: 1px solid #272727;
        background: transparent;
    }

    .second-ch input {
        display: block;
        border:none !important;
        padding: 10px !important;
        width: 305px;
        text-align: center;
        color: #fff;
        margin-top: 1rem !important;
        margin-bottom: 1rem !important;
        background: linear-gradient(115.4deg, #F26457 -8.89%, #960036 98.4%);
    }

    #qtVenda {
        background: transparent !important;
        border: none !important;
        outline: none !important;
        width: 50px !important;
        text-align:center !important;
    }

    .vl {
        padding-bottom: 10px !important;
        border-bottom: 3px solid #c4c4c4;
        margin-bottom: 2rem !important;
        display: inline-block !important;
    }

</style>
<div class="container-my">
    <h2>Carrinho</h2>

    <table class="table-my ">
        <tr class="items-text cab-my">
            <td>Produto</td>
            <td>Quantidade</td>
            <td>Valor Unitário</td>
            <td>Valor Total</td>
            <td></td>
        </tr>

        @foreach (var item in Model.ItensPedido)
        {

            <tr class="items-text ">
                <td>@item.nm_produto</td>
                <td>
                    @Html.ActionLink("  -  ", "RetirarCarrinho", new { id = item.cd_produto, pre = item.vl_unitario }, null)

                    <input value="@item.qt_venda" name="qt" id="qtVenda" />


                    @Html.ActionLink("  +  ", "AdicionarCarrinho", new { id = item.cd_produto, pre = item.vl_unitario }, null)
                </td>
                <td>@item.vl_unitario</td>
                <td>@item.vl_parcial</td>
                <td class="remover">@Html.ActionLink("Remover", "ExcluirItem", new { id = item.ItemPedidoID }, null)</td>
            </tr>
        }

    </table>

    <hr />

    <h3 class="vl"> Valor Total: @Model.vlTotal</h3>

    <div class="links-items">
        <div class="first-ch">
            @Html.ActionLink("Continuar Comprando", "Index", "Loja")
        </div>

        @using (Html.BeginForm("SalvarCarrinho", "Compra", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="pagamento">
                @Html.DropDownList("pagamento", "Escolha a forma de pagamento")
            </div>


            <div class="second-ch">
                <input type="submit" name="btn" value="Finalizar Compra" />
            </div>
        }
    </div>
</div>

Projeto_Pet/TCC/Views/Compra/confVenda.cshtml
@{ ViewBag.Title = "confVenda"; }

<style>
    #containerConf {
        color: #fff;
        width: 100%;
        display: flex;
        background: #33E47A;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        height: 100vh;
    }

        #containerConf a {
            display: block !important;
            text-align: center;
            background-color: #fff !important;
            font-weight: bold !important;
            width: 150px !important;
            color: #33E47A !important;
            padding: 1rem;
            border-radius: .25rem;
        }
</style>


<div id="containerConf">
    <h2>
        <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="#fff" viewBox="0 0 256 256"><rect width="256" height="256" fill="none"></rect><polyline points="172 104 113.3 160 84 132" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="16"></polyline><circle cx="128" cy="128" r="96" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-width="16"></circle></svg>
        <span>Compra efetuada com sucesso</span>
    </h2>
    <br />
    @Html.ActionLink("Voltar", "Index", "Loja")
</div>